const WORKSPACE_HEADER_HEIGHT = 68;
const WORKSPACE_NAV_HEIGHT = 52;
const WORKSPACE_SHELL_HEIGHT = WORKSPACE_HEADER_HEIGHT + WORKSPACE_NAV_HEIGHT;
const WORKSPACE_MAX_WIDTH = 1720;

export {
  WORKSPACE_HEADER_HEIGHT,
  WORKSPACE_MAX_WIDTH,
  WORKSPACE_NAV_HEIGHT,
  WORKSPACE_SHELL_HEIGHT,
};
